import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { RoomEnvironment } from './vendor/RoomEnvironment.js';
import { createExterior, box, mat, palm, sphere, M, batch } from './model.js';
import { createInterior, rooms, orderedRooms, inside, world } from './interior.js';
import { PLAN } from './plan.js';
import { APARTMENTS } from './apartments.js';
import { loadInteriorAssets } from './surfaces.js';
import { createPositionMap } from './position-map.js';
import { createWalkNavigation } from './walk-navigation.js';
import { RectAreaLightUniformsLib } from './vendor/addons/lights/RectAreaLightUniformsLib.js';
import { EffectComposer } from './vendor/addons/postprocessing/EffectComposer.js';
import { RenderPass } from './vendor/addons/postprocessing/RenderPass.js';
import { SSAOPass } from './vendor/addons/postprocessing/SSAOPass.js';
import { OutputPass } from './vendor/addons/postprocessing/OutputPass.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#scene'),stage=$('.stage');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(2,Math.max(1.5,devicePixelRatio)));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dbe5e9');scene.fog=new THREE.Fog('#dbe5e9',85,190);
const camera=new THREE.PerspectiveCamera(42,1,.045,350);camera.position.set(37,24,-43);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,8,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=15;controls.maxDistance=85;
const pmrem=new THREE.PMREMGenerator(renderer),environment=new RoomEnvironment();scene.environment=pmrem.fromScene(environment,.04).texture;scene.environmentIntensity=.48;environment.dispose();pmrem.dispose();
const sun=new THREE.DirectionalLight('#fff1d5',3);sun.position.set(-23,38,-25);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35,near:1,far:110});sun.shadow.normalBias=.04;sun.shadow.bias=-.0003;sun.shadow.radius=3;scene.add(sun);const sky=new THREE.HemisphereLight('#d5e7f1','#a49b80',1.7);scene.add(sky);
RectAreaLightUniformsLib.init();
const assets=await loadInteriorAssets(renderer);
const exterior=createExterior();scene.add(exterior);
const interior=createInterior(assets);scene.add(interior.root);interior.root.visible=false;
const outdoor=new THREE.Group();scene.add(outdoor);box(outdoor,0,-.12,0,240,.2,240,mat('outside','#acbbaa'));box(outdoor,0,.01,-14,200,.02,7,mat('outsideRoad','#8a9294'));for(const x of [-18,-7,5,17]){palm(outdoor,x,12,5.8);sphere(outdoor,x,.6,12,1.3,.6,1,M.leaf);}for(const x of [-18,18])for(const z of [-6,1,7])palm(outdoor,x,z,5);batch(outdoor);outdoor.visible=false;
const composer=new EffectComposer(renderer);composer.renderTarget1.samples=4;composer.renderTarget2.samples=4;composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,stage.clientWidth,stage.clientHeight);ao.kernelRadius=.65;ao.minDistance=.001;ao.maxDistance=.08;composer.addPass(ao);composer.addPass(new OutputPass());
const highlight=new THREE.Mesh(new THREE.BoxGeometry(30.1,.065,12.9),new THREE.MeshBasicMaterial({color:'#d8b46f',transparent:true,opacity:.72}));scene.add(highlight);highlight.position.y=3.1;highlight.visible=false;
const state={mode:'exterior',flat:'A',floor:1,sunset:false,room:'a-living',overview:false};
const positionMap=createPositionMap({getState:()=>state,getPose:()=>({x:camera.position.x,z:camera.position.z,yaw}),onOpen:()=>{keys.clear();walkNavigator.cancel();},visit:id=>{state.room=id;setMode('walk');}});
let yaw=0,pitch=0,transition=null,lastTime=performance.now(),frameCount=0,lastStats=performance.now(),keys=new Set(),drag=null,tags=[],lastRoomCheck=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){const previousAspect=camera.aspect;renderer.setSize(stage.clientWidth,stage.clientHeight,false);composer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();if(window.__tour&&state.mode!=='walk'&&Math.abs(camera.aspect-previousAspect)>.2)resetView();}new ResizeObserver(resize).observe(stage);resize();
function toast(s){$('#toast').textContent=s;$('#toast').style.opacity='1';clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').style.opacity='0',3000);}
function animateCamera(position,target,duration=900){transition={start:performance.now(),duration:reduced?1:duration,from:camera.position.clone(),to:new THREE.Vector3(...position),targetFrom:controls.target.clone(),targetTo:new THREE.Vector3(...target)};}
function overviewView(all=false){state.overview=all;makeTags();$('#overview-button').textContent=all?'Focus apartment':'Whole floor';camera.fov=42;camera.updateProjectionMatrix();const center=all?0:state.flat==='A'?9.8:state.flat==='C'?-8.7:.1;const width=all?32:state.flat==='B'?14:14;const depth=all?15:14;const dist=Math.max(depth,width/Math.max(camera.aspect,.5))*(all?1.12:.9);animateCamera([center+dist*.12,dist*1.18,dist*.98],[center,0,all?0:state.flat==='B'?2:0]);controls.minDistance=8;controls.maxDistance=60;controls.maxPolarAngle=Math.PI*.44;}
function resetView(){if(state.mode==='walk'){visitRoom(state.room==='common'?orderedRooms(state.flat)[0].id:state.room);return;}if(state.mode==='dollhouse'){overviewView(state.overview);return;}camera.fov=42;camera.updateProjectionMatrix();const d=camera.aspect<1?1.5:1;animateCamera([37*d,24*d,-43*d],[0,8,0]);controls.minDistance=15;controls.maxDistance=100;controls.maxPolarAngle=Math.PI*.49;}
function flatUI(){for(const [id,a] of Object.entries(APARTMENTS)){const b=document.querySelector(`[data-flat="${id}"]`);b.style.setProperty('--apartment',a.color);b.style.setProperty('--apartment-pale',a.pale);}for(const b of $$('[data-flat]')){const on=b.dataset.flat===state.flat;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);}$('#enter-home').innerHTML=`Enter apartment ${state.flat} <span>↗</span>`;$('#minimap-flat').textContent=`${state.flat}`;stage.style.setProperty('--apartment',APARTMENTS[state.flat].color);}
function setFlat(flat){if(!PLAN.flats[flat])return;state.flat=flat;state.room=orderedRooms(flat)[0].id;flatUI();updateRoomList();makeTags();if(state.mode==='walk')visitRoom(state.room);if(state.mode==='dollhouse')overviewView();updateHeadings();}
function updateHeadings(){const f=PLAN.flats[state.flat];$('#scene-kicker').textContent=state.mode==='exterior'?'THE ADDRESS':state.mode==='walk'?'INSIDE YOUR RESIDENCE':'A DIFFERENT PERSPECTIVE';$('#scene-title').textContent=state.mode==='exterior'?'Anugraha, in perspective':state.mode==='walk'?`Apartment ${state.flat} · Floor ${String(state.floor).padStart(2,'0')}`:state.overview?'The complete floor':`Apartment ${state.flat}, opened up`;$('#scene-subtitle').textContent=state.mode==='exterior'?'Jayanagar 2nd Street · LIC Colony':`${f.bedrooms} bedrooms · ${f.advertisedAreaSqFt.toLocaleString()} sq. ft. · ${state.mode==='walk'?'Illustrative interiors':'Typical floor '+state.floor}`;if(state.mode==='dollhouse'&&state.overview)$('#scene-subtitle').textContent=`Apartments A, B and C · Shared lobby · Floor ${state.floor}`;$('#overview-button').hidden=state.mode!=='dollhouse';}
const overviewButton=document.createElement('button');overviewButton.id='overview-button';overviewButton.className='pill';overviewButton.textContent='Whole floor';overviewButton.hidden=true;$('.scene-tools').prepend(overviewButton);overviewButton.onclick=()=>{overviewView(!state.overview);overviewButton.textContent=state.overview?'Focus apartment':'Whole floor';updateHeadings();};
function setMode(mode){if(!['exterior','dollhouse','walk'].includes(mode))return;const previous=state.mode;walkNavigator.cancel();state.mode=mode;keys.clear();transition=null;controls.enabled=mode!=='walk';exterior.visible=mode==='exterior';interior.root.visible=mode!=='exterior';outdoor.visible=mode==='walk';outdoor.position.y=-state.floor*3.1;interior.setMode(mode==='walk');stage.classList.toggle('walk',mode==='walk');$('#room-panel').hidden=mode!=='walk';$('#minimap-wrap').hidden=mode!=='walk';$('#touch-move').hidden=mode!=='walk';$('#room-tags').hidden=mode!=='dollhouse';highlight.visible=false;scene.environmentIntensity=mode==='walk'?.55:.48;sky.intensity=mode==='walk'?1.5:1.7;ao.kernelRadius=mode==='exterior'?1.5:.45;$('#view-hint').innerHTML=mode==='walk'?'<span>CLICK FLOOR TO MOVE</span><i></i><span>DRAG TO LOOK · W A S D</span>':'<span>DRAG TO ROTATE</span><i></i><span>SCROLL TO ZOOM</span>';
for(const b of $$('[data-mode]')){const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);}if(mode==='walk'){camera.fov=68;camera.updateProjectionMatrix();updateRoomList();visitRoom(state.room==='common'?orderedRooms(state.flat)[0].id:state.room);if(previous!=='walk')toast('Click clear floor space to walk there. Drag to look around.');}else if(mode==='dollhouse'){overviewView();makeTags();}else resetView();updateHeadings();}
function updateRoomList(){const list=orderedRooms(state.flat);$('#room-select').replaceChildren(...list.map(r=>{const opt=document.createElement('option');opt.value=r.id;opt.textContent=r.label;return opt;}));$('#room-select').value=state.room;}
function updateRoomPanel(room){$('#minimap-flat').textContent=room.flat;const list=orderedRooms(room.flat),index=list.findIndex(r=>r.id===room.id);$('#room-count').textContent=`${String(index+1).padStart(2,'0')} / ${list.length}`;$('#room-name').textContent=room.label;$('#room-dim').textContent=room.dim||'Shared space';$('#room-select').value=room.id;}
function visitRoom(id){walkNavigator.cancel();const room=rooms.find(r=>r.id===id);if(!room)return;if(state.flat!==room.flat){state.flat=room.flat;flatUI();updateRoomList();makeTags();}state.room=id;const [x,z]=room.visit;camera.position.set(x,1.62,z);yaw=Math.atan2(-(room.look[0]-x),-(room.look[1]-z));pitch=room.kind==='balcony'?-.28:room.kind==='bathroom'?-.25:room.kind==='kitchen'?-.13:-.07;camera.rotation.set(pitch,yaw,0,'YXZ');transition=null;updateRoomPanel(room);updateHeadings();canvas.focus({preventScroll:true});}
function makeTags(){$('#room-tags').replaceChildren();tags=[];if(state.overview&&state.mode==='dollhouse'){for(const [id,a] of Object.entries(APARTMENTS)){const b=document.createElement('button');b.className='room-tag apartment-tag';b.textContent=`Apartment ${id} · ${a.beds}`;b.style.setProperty('--apartment',a.color);b.style.borderColor=a.color;b.onclick=()=>setFlat(id);$('#room-tags').append(b);tags.push({el:b,point:new THREE.Vector3(id==='A'?9.2:id==='C'?-9.4:0,2.8,id==='B'?3.2:0)});}return;}for(const room of orderedRooms(state.flat).filter(r=>!['bathroom','utility','foyer'].includes(r.kind))){const b=document.createElement('button');b.className='room-tag';b.textContent=room.label;b.setAttribute('aria-label',`Enter ${room.label} in apartment ${room.flat}`);b.onclick=()=>{state.room=room.id;setMode('walk');};$('#room-tags').append(b);tags.push({el:b,point:new THREE.Vector3(room.visit[0],.2,room.visit[1])});}}
function wallDistance(x,z,w){
 const [ax,az]=w.a,[bx,bz]=w.b,dx=bx-ax,dz=bz-az,length=Math.hypot(dx,dz);
 const along=((x-ax)*dx+(z-az)*dz)/length,across=((x-ax)*-dz+(z-az)*dx)/length;
 return Math.hypot(Math.max(-along,along-length,0),Math.max(Math.abs(across)-w.width/2,0));
}
function canStand(x,z,radius=.22){const points=Object.values(interior.footprints);if(!points.some(poly=>inside(x,z,poly)||inside(x+.1,z,poly)||inside(x-.1,z,poly)||inside(x,z+.1,poly)||inside(x,z-.1,poly)))return false;const shaft=PLAN.rooms.find(r=>r.kind==='void');if(inside(x,z,shaft.polygonWorldXZ))return false;for(const wall of interior.collisions)if(wallDistance(x,z,wall)<radius)return false;for(const b of interior.furnitureBounds)if(x>b.minX-radius&&x<b.maxX+radius&&z>b.minZ-radius&&z<b.maxZ+radius)return false;return true;}
const walkNavigator=createWalkNavigation({scene,interior,camera,canvas,canStand,onStatus:active=>{$('#walk-stop').hidden=!active;}});
$('#walk-stop').onclick=()=>walkNavigator.cancel();
function move(dt){let forward=(keys.has('w')||keys.has('arrowup')||keys.has('forward')?1:0)-(keys.has('s')||keys.has('arrowdown')||keys.has('backward')?1:0);let side=(keys.has('d')||keys.has('arrowright')||keys.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||keys.has('left')?1:0);if(!forward&&!side)return;walkNavigator.cancel();const norm=Math.hypot(forward,side);forward/=norm;side/=norm;const speed=1.55*dt;const dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed;const steps=Math.max(1,Math.ceil(speed/.05));for(let n=0;n<steps;n++){if(canStand(camera.position.x+dx/steps,camera.position.z))camera.position.x+=dx/steps;if(canStand(camera.position.x,camera.position.z+dz/steps))camera.position.z+=dz/steps;}}
canvas.addEventListener('pointerdown',e=>{if(state.mode!=='walk')return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});});
canvas.addEventListener('pointermove',e=>{if(!drag||state.mode!=='walk')return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5){drag.moved=true;walkNavigator.cancel();}yaw-=(e.clientX-drag.x)*.004;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-drag.y)*.003,-1.25,1.25);drag.x=e.clientX;drag.y=e.clientY;});
canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved&&state.mode==='walk'){if(!walkNavigator.click(e.clientX,e.clientY))toast('Choose clear floor space, or select a room from the map.');}drag=null;});
for(const event of ['pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>drag=null);
window.addEventListener('keydown',e=>{if(e.key==='Escape')walkNavigator.cancel();if(state.mode!=='walk'||$('dialog[open]')||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();keys.add(key);}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();drag=null;});document.addEventListener('visibilitychange',()=>keys.clear());
for(const b of $$('[data-move]')){b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.move);b.setPointerCapture(e.pointerId);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.move));}
for(const b of $$('[data-flat]'))b.onclick=()=>setFlat(b.dataset.flat);for(const b of $$('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);
for(const b of $$('[data-floor]'))b.onclick=()=>{state.floor=+b.dataset.floor;for(const el of $$('[data-floor]')){const on=el===b;el.classList.toggle('active',on);el.setAttribute('aria-pressed',on);}outdoor.position.y=-state.floor*3.1;updateHeadings();if(state.mode==='exterior'){highlight.position.y=3.1+(state.floor-1)*3.1;highlight.visible=true;clearTimeout(b.timer);b.timer=setTimeout(()=>highlight.visible=false,2600);}toast(`Floor ${state.floor} · typical plan with apartments A, B and C`);};
$('#enter-home').onclick=()=>{state.room=orderedRooms(state.flat)[0].id;setMode('walk');};$('#room-select').onchange=e=>visitRoom(e.target.value);for(const [id,delta] of [['#prev-room',-1],['#next-room',1]])$(id).onclick=()=>{const list=orderedRooms(state.flat),i=list.findIndex(r=>r.id===state.room);visitRoom(list[(i+delta+list.length)%list.length].id);};
$('#lighting').onclick=()=>{state.sunset=!state.sunset;sun.color.set(state.sunset?'#ffbf86':'#fff1d5');sun.position.set(state.sunset?-38:-23,state.sunset?13:38,-25);sun.intensity=state.sunset?2.4:3;scene.background.set(state.sunset?'#d8c6bc':'#dbe5e9');scene.fog.color.copy(scene.background);$('#light-label').textContent=state.sunset?'Golden hour':'Daylight';$('#lighting').setAttribute('aria-pressed',state.sunset);};
$('#reset-view').onclick=resetView;$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Full screen is unavailable in this browser.');}};
for(const [button,dialog] of [['#help-button','#help-dialog'],['#plan-top','#plan-dialog'],['#view-plan','#plan-dialog'],['#model-info','#info-dialog']])$(button).onclick=()=>{keys.clear();$(dialog).showModal();};
for(const d of $$('dialog')){d.querySelector('.close-dialog').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
$('.brand').onclick=e=>{e.preventDefault();setMode('exterior');};
controls.addEventListener('start',()=>transition=null);
flatUI();updateRoomList();makeTags();updateHeadings();if(camera.aspect<1)resetView();
renderer.setAnimationLoop(now=>{const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;if(state.mode==='walk'){if(!$('dialog[open]')){move(dt);const travel=walkNavigator.update(dt);if(travel){const targetYaw=Math.atan2(-travel.dx,-travel.dz),delta=Math.atan2(Math.sin(targetYaw-yaw),Math.cos(targetYaw-yaw));yaw+=delta*Math.min(1,dt*3);pitch+=(-.1-pitch)*Math.min(1,dt*2.4);}}camera.rotation.set(pitch,yaw,0,'YXZ');positionMap.render(now);if(now-lastRoomCheck>500){lastRoomCheck=now;const r=rooms.find(r=>inside(camera.position.x,camera.position.z,r.polygonWorldXZ));if(r&&r.id!==state.room){state.room=r.id;if(r.flat!==state.flat){state.flat=r.flat;flatUI();updateRoomList();updateHeadings();makeTags();}updateRoomPanel(r);updateHeadings();}else if(!r&&inside(camera.position.x,camera.position.z,interior.footprints.common)){$('#room-name').textContent='Shared lobby';$('#room-dim').textContent='Entrances to A, B and C';$('#room-count').textContent='COMMON';$('#room-select').value='';$('#minimap-flat').textContent='LOBBY';state.room='common';$('#scene-title').textContent=`Shared lobby · Floor ${String(state.floor).padStart(2,'0')}`;$('#scene-subtitle').textContent='Separate entrances to apartments A, B and C';}}}else{if(transition){const t=Math.min(1,(now-transition.start)/transition.duration),k=1-(1-t)**3;camera.position.lerpVectors(transition.from,transition.to,k);controls.target.lerpVectors(transition.targetFrom,transition.targetTo,k);if(t===1)transition=null;}controls.update();}
if(state.mode==='dollhouse'){for(const t of tags){const p=t.point.clone().project(camera);const x=(p.x*.5+.5)*stage.clientWidth,y=(-p.y*.5+.5)*stage.clientHeight;t.el.style.left=x+'px';t.el.style.top=y+'px';t.el.hidden=p.z>1||p.z<0||x<0||x>stage.clientWidth||y<105||y>stage.clientHeight-112;}}
$('.compass svg').style.transform=`rotate(${Math.atan2(camera.position.x-controls.target.x,camera.position.z-controls.target.z)*180/Math.PI}deg)`;ao.ssaoMaterial.uniforms.cameraProjectionMatrix.value.copy(camera.projectionMatrix);ao.ssaoMaterial.uniforms.cameraInverseProjectionMatrix.value.copy(camera.projectionMatrixInverse);composer.render();frameCount++;if(now-lastStats>1500){canvas.dataset.fps=String(Math.round(frameCount*1000/(now-lastStats)));canvas.dataset.drawCalls=String(renderer.info.render.calls);frameCount=0;lastStats=now;}});
requestAnimationFrame(()=>{$('#loading').style.opacity='0';setTimeout(()=>$('#loading')?.remove(),550);});
// Read-only diagnostics support geometry and interaction verification of this local model.
window.__tour={walkNavigator,assets,state,renderer,scene,camera,controls,interior,rooms,canStand,composer};

// Optional browser-native agent navigation uses exactly the same tour actions as the controls.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tools=[{name:'inspect_property_tour',title:'Inspect property tour',description:'Read the current view and the room destinations in the Arjith Anugraha virtual tour.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({view:{...state},apartments:PLAN.flats,rooms:rooms.map(r=>({id:r.id,flat:r.flat,name:r.label,dimensions:r.dim}))})},{name:'navigate_property_tour',title:'Navigate property tour',description:'Open an apartment, room, or view in this local 3D tour. Changes only the visible tour.',inputSchema:{type:'object',properties:{flat:{type:'string',enum:['A','B','C']},mode:{type:'string',enum:['exterior','dollhouse','walk']},room:{type:'string'}},required:['flat','mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{if(!input||!PLAN.flats[input.flat]||!['exterior','dollhouse','walk'].includes(input.mode))throw new Error('Choose a valid apartment and view.');if(input.room&&!rooms.some(r=>r.id===input.room&&r.flat===input.flat))throw new Error('Room does not belong to this apartment.');setFlat(input.flat);if(input.room)state.room=input.room;setMode(input.mode);await new Promise(resolve=>setTimeout(resolve,reduced?30:950));return{...state};}}];
 tools.push({name:'walk_to_property_room',title:'Walk to a property room',description:'Physically walk from the current position through the modeled floor to a room, using the same collision-aware movement as floor clicks. Does not teleport. An optional planPoint [x,y] in source floor-plan pixels selects a precise point inside that room. Returns arrival evidence or an obstruction.',inputSchema:{type:'object',properties:{room:{type:'string'},planPoint:{type:'array',items:{type:'number'},minItems:2,maxItems:2}},required:['room'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async({room:id,planPoint})=>{
  const room=rooms.find(r=>r.id===id);if(!room)throw new Error('Unknown room.');if(state.mode!=='walk')throw new Error('Enter walkthrough first.');const target=planPoint?world(planPoint):room.visit;if(!inside(...target,room.polygonWorldXZ))throw new Error('Point must be inside the selected room.');if(!walkNavigator.begin(target))return {arrived:false,room:id,reason:'No clear route'};
  const started=performance.now();while(walkNavigator.active&&performance.now()-started<45000)await new Promise(resolve=>setTimeout(resolve,100));
  const result=walkNavigator.lastResult;if(walkNavigator.active){walkNavigator.cancel('timeout');return {arrived:false,room:id,...walkNavigator.lastResult};}
  const arrived=result?.reason==='arrived'&&result.distanceRemaining<.03;
  if(arrived){state.room=room.id;state.flat=room.flat;flatUI();updateRoomList();updateRoomPanel(room);updateHeadings();yaw=Math.atan2(-(room.look[0]-camera.position.x),-(room.look[1]-camera.position.z));pitch=room.kind==='bathroom'?-.25:room.kind==='balcony'?-.28:-.1;camera.rotation.set(pitch,yaw,0,'YXZ');}
  return {arrived,room:id,...result};
 }});
 for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
